# Generated by Django 3.2.4 on 2021-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=100)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
