# Generated by Django 3.1.5 on 2021-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_auto_20210622_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockmodel',
            unique_together=set(),
        ),
    ]
